@startuml

NanterreUniversityAdmin -> Site_Admin: Connection
activate Site_Admin


Site_Admin -> BDD: Authentication Request
activate BDD

alt successful

    BDD -> Site_Admin: Authentication Accepted
    Site_Admin -> NanterreUniversityAdmin : Access control panel

        alt Add/Edit news
            NanterreUniversityAdmin -> Site_Admin: Add/Edit news

        else Add/Edit POI on the map of the campus
            NanterreUniversityAdmin -> Site_Admin: Add/Edit POI on the map of the campus

        else Add student
             NanterreUniversityAdmin -> Site_Admin: Add student

        else Manage student
             NanterreUniversityAdmin -> Site_Admin: Manage student

        else Manage How To ?
             NanterreUniversityAdmin -> Site_Admin: Manage How To ?

        else Add/Edit language words
            NanterreUniversityAdmin -> Site_Admin: Add/Edit language words

        else Add/Edit administrative contacts
             NanterreUniversityAdmin -> Site_Admin: Add/Edit administrative contacts

        else Add University
             NanterreUniversityAdmin -> Site_Admin: Add University

        else Manage Universities
             NanterreUniversityAdmin -> Site_Admin: Manage Universities
        end

else failure

    BDD -> Site_Admin: Authentication Failure
    Site_Admin->NanterreUniversityAdmin : Repeat Connection
end


@enduml