@startuml

class Student{
    String login
    String mdp
    String mail
    String nationality
}

class ToDoList{
    List <String> toDo

}

class HowTo{

}

class Culture{


}


class Map{


}

class MapInfo{
    String name
    String 


}


class Contacts{


}

class Contact{
    String firstName
    String lastName
    String mail
    String job




}


class LearningLanguage{


}

class Word{
    String localWord
    String nationalyWord

}



@enduml