@startuml

Student -> Smartphone_Android: Connection
activate Smartphone_Android


Smartphone_Android -> BDD: Authentication Request
activate BDD

alt successful

    BDD -> Smartphone_Android: Authentication Accepted
    Smartphone_Android->Student : Show news

        alt How to?
            Student -> Smartphone_Android: How to?
            Smartphone_Android -> Student: Show list how to?

        else Contact
            Student -> Smartphone_Android: Contact
            Smartphone_Android -> Student: Show list Contact

        else To do list
             Student -> Smartphone_Android: To do list
             Smartphone_Android -> Student: Show to do list

        else Learning french
             Student -> Smartphone_Android: Learning french
             Smartphone_Android -> Student: Show french words

        else Map
             Student -> Smartphone_Android: Map
             Smartphone_Android -> Student: Show univesity map

        else Learning local culture
             Student -> Smartphone_Android: Learning local culture
             Smartphone_Android -> Student: Show local culture

        end

else failure

    BDD -> Smartphone_Android: Authentication Failure
    Smartphone_Android->Student : Repeat connection
end


@enduml