@startuml

UniversityAdmin -> Site_Admin: Connection
activate Site_Admin


Site_Admin -> BDD: Authentication Request
activate BDD

alt successful

    BDD -> Site_Admin: Authentication Accepted


        alt Add/Edit news
            UniversityAdmin -> Site_Admin: Add/Edit news

        else Add/Edit POI on the map of the campus
            UniversityAdmin -> Site_Admin: Add/Edit POI on the map of the campus

        else Add student
             UniversityAdmin -> Site_Admin: Add student

        else Manage student
             UniversityAdmin -> Site_Admin: Manage student

        else Manage How To ?
             UniversityAdmin -> Site_Admin: Manage How To ?

        else Add/Edit language words
             UniversityAdmin -> Site_Admin: Add/Edit language words

        else Add/Edit administrative contacts
             UniversityAdmin -> Site_Admin: Add/Edit administrative contacts

        end

else failure

    BDD -> Site_Admin: Authentication Failure
    Site_Admin->UniversityAdmin : Repeat Connection
end


@enduml