@startuml

left to right direction

skinparam packageStyle rect

 :Student: as User
 :University: as Univ
 :Nanterre University\nAdmin: as Admin

 Univ<-Admin

rectangle Nanterasmus{

  User -- (Consult News)
  User -- (How to ?)
  User -- (Manage TODO List)
  User -- (Contact)
  User -- (Learning local culture)
  User -- (Consult a Map of the campus)
  User -- (Learning language)

  Univ -- (Add/Edit News)
  Univ -- (Add/Edit POI on the map of the campuis)
  Univ -- (Add Student)
  Univ -- (Manage Student)
  Univ -- (Manage "How To ?" Part)
  Univ -- (Add/Edit language words)
  Univ -- (Add/Edit administrative contacts)
  (Add Student) <. (Manage Student) : extends

  Admin -- (Add University)
  Admin -- (Manage Universities)
  (Add University) <. (Manage Universities) : extends


}

@enduml