@startuml

left to right direction

skinparam packageStyle rect

 :Student: as User
 :University: as Partner
 :Nanterre University\nAdmin: as Admin

 Partner<-Admin

rectangle Nanterasmus{

  User -- (Consult News)
  User -- (How to ?)
  User -- (Manage TODO List)
  User -- (Contact)
  User -- (Learning local culture)
  User -- (Consult a Plan of the campus)
  User -- (Learning language)

  Partner -- (Add/Edit News)
  Partner -- (Add Student)
  Partner -- (Manage Student)
  Partner -- (Manage "How To ?" Part)
  Partner -- (Add/Edit language words)
  Partner -- (Add/Edit administrative contacts)
  (Add Student) <. (Manage Student) : extends

  Admin -- (Add Partner)
  Admin -- (Manage Partner)
  (Manage Partner) .> (Add Partner) : extends


}

@enduml